### ISSUE TITLE
Possibly integrate with HeadlessUI

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#116]
There's a cool project by @tailwindlabs that creates components without styles and there is an early version by @GavinJoyce https://github.com/GavinJoyce/ember-headlessui that implements it for Ember. Since this project uses tailwind and ember, it might be a good combo to build upon the headless components where possible.

Although the Ember version is still young and the whole HeadlessUI project too.

**Comment by josemarluedke** [comment]
I agree it would be nice to share some of the functionality, but there are a few things that it seems the ember-headlessui addon is going in a different direction than I would like to take Frontile.
 
The main one being that the ember addon is not broken-down in multiple packages. I would not like to add a large dependency to each of our packages.

The other one is that I would like to make our components glimmer only (ember-headlessui seems to be at this point), and maybe even compatible with glimmer standalone for example. So, I would not like to have a dependency holding us back. Looking even further, I'm eager to move Frontile to Template Imports, so one more reason...


Closing this issue, but I'm open to keeping a conversation going if things change.
