### ISSUE TITLE
Expose `focusTrapOptions` on Overlay

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#119]
Currently I have to disable it for ember-power-datepicker because it prevents events from firing. Would prefer to just configure it.

**Comment by josemarluedke** [comment]
Yeah, this is definitely needed to have control in a few cases. I actually already have added this in #114 which is unreleased. I planning to do a release today.

**Comment by knownasilya** [comment]
Looks like master doesn't have it passed down here https://github.com/josemarluedke/frontile/blob/master/packages/overlays/addon/components/modal/index.hbs#L10

**Comment by josemarluedke** [comment]
@knownasilya You're right. I totally messed that up. Should be up in #120.
