### ISSUE TITLE
Modal footer shadow renders over UI

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#138]
<img width="1403" alt="Screen Shot 2021-01-23 at 5 12 45 PM" src="https://user-images.githubusercontent.com/34726/105615389-4b088e80-5d9e-11eb-83fd-e0302bd9efe8.png">

Looks like an `undefined` in the css.

Code looks like so:

```hbs
<m.Footer class='flex justify-between'>
  <Button
    @appearance='minimal'
    class='mr-4'
    {{on 'click' this.toggleNewPostModal}}
  >
    Cancel
  </Button>

  <Button
    @type='submit'
    @intent='primary'
    disabled={{this.createPost.isRunning}}
  >
    {{if this.createPost.isRunning 'Creating..' 'Create & Write'}}
  </Button>
</m.Footer>
```

**Comment by josemarluedke** [comment]
Do you still have this issue? It might be because of the tailwind version you had (<2).

**Comment by knownasilya** [comment]
Will check next time I'm in the app

**Comment by josemarluedke** [comment]
Will close this. Re-open if you still encounter this issue.
