### ISSUE TITLE
Some buttons have font size 0

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#139]
```css
.btn-outlined--xs {
    font-size: 0;
}
```

**Comment by josemarluedke** [comment]
This seems a bit off, I just checked in the docs site, and it looks good.

Are you using TailwindCSS v2?

**Comment by knownasilya** [comment]
No, 1.8.0

**Comment by josemarluedke** [comment]
So, if you are using TailwindCSS < 2, you will need to use Frontile v0.8.0 as > v0.9.0 requires TailwindCSS v2.

https://github.com/josemarluedke/frontile/releases/tag/v0.9.0

**Comment by knownasilya** [comment]
Used 2.0.0-compat and it works, thanks!
