### ISSUE TITLE
Drawer + Power Select

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/frontile#148]
I have a code that goes something like this (only showing important fields):

```hbs
<Drawer @isOpen={{true}} as |d|>
    <PowerSelect @searchEnabled={{true}} as |el|>
      {{yield el}}
    </PowerSelect>
</Drawer>
```

The problem then is that the `input` search field in `power-select` is not reachable. It renders. I could click it, but it won't get the focus.

My theory is that since the `power-select` itself is rendered through a wormhole and since `drawer` is trying to keep the focus, it just does not work.

I figured out that in my case when I set `@disableFocusTrap={{true}}` on the `drawer` it starts working again. 

Just wanted to bring this issue to attention. Maybe there is a better way? And also to "document" it for future travellers.

Feel free to close if this is "works as intended".

**Comment by josemarluedke** [comment]
@MichalBryxi Thanks for reaching out for clarification.

Yeah, unfortunately, this is a known problem. Power Select will insert the content outside of the Drawer content, then focus-trap will prevent accessing it. 

There are two ways to avoid this problem:
1. Disable focus trap, which might not be the best approach, but does fix the issue.
2. Render the power select in place `@renderInPlace={{true}}`. This would render the power select inside of the drawer, allowing focus-trap to not block access to it. 

Also, worth noting that this problem will exist in Modal as well.


This could be a nice addition to the docs, do you want to send PR for that?

**Comment by MichalBryxi** [comment]
This edge case is also probably worth noting:

When you have `@renderInPlace={{false}}` on the power-select, and your dropdown is at the bottom of the screen, then it will overflow over the `drawer.footer` and in extreme cases become not reachable as you won't be able to "scroll" to the options.
![Screenshot 2021-02-19 at 11 16 47](https://user-images.githubusercontent.com/847473/108498882-63889d80-72a5-11eb-95fb-db6e9ca0712f.png)

When you have `@renderInPlace={{true}}` on the power-select, it gets rendered into the `drawer.body` and this becomes part of the scrollable area of the drawer thus the bug described above should not happen.
![Screenshot 2021-02-19 at 11 15 38](https://user-images.githubusercontent.com/847473/108498760-4358de80-72a5-11eb-8d06-17e45e558f76.png)

Will try to formulate the findings into the docs 👍
