### ISSUE TITLE
Modal closes when it shouldn't

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#153]
The scenario is this:

Click and hold on the modal, drag the mouse over the overlay, release, modal closes. This is unexpected, since you could be highlighting something or using s slider and accidentally veer off the modal body.

**Comment by josemarluedke** [comment]
@knownasilya do you have any suggestions on how to fix this issue?

**Comment by knownasilya** [comment]
Check that the click even originated on the backdrop before closing
