### ISSUE TITLE
What is "core" package?

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/frontile#303]
In [installation documentation](https://github.com/josemarluedke/frontile/blob/main/docs/installation.md?plain=1#L12) it says:

> Independently of which packages you will use, you will need to have the **Core** and Theme package installed.

But there is no `@frontile/core` package mentioned. Is this a typo?

**Comment by cloke** [comment]
Looks like it might be a typo. https://github.com/josemarluedke/frontile/commit/72218220402e459887c87bcae28b5545f83e43fd
