### ISSUE TITLE
Input's Label does not seem to have customisable classes?

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/frontile#332]
Looking at [the Input docs](https://frontile.dev/docs/forms/input) where it says that `<Input>` has following `@classes`:
```
SlotsToClasses<'base' | 'input' | 'innerContainer' | 'startContent' | 'endContent'>
```
 and [this piece of code](https://github.com/josemarluedke/frontile/blob/main/packages/forms/src/components/form-control.gts#L104) I don't think it's easy to ad-hoc customise appearance of `Label` on `Input`?

**Comment by josemarluedke** [comment]
You are right, there is no way to set the class of the label. 

However, here is how you could customize the label.

```gts
import {
  Input
} from '@frontile/forms';

const MyCustomLabel = <template>
  This is a custom label. <span class="text-danger">Cool right?</span>
</template> as never;

<template>
    <Input
      @name="field-1"
      @label={{MyCustomLabel}}
      @description="Cool field"
      @isRequired={{true}}
      @isClearable={{true}}
    />
<template>
```

**Comment by MichalBryxi** [comment]
Thank you! I guess unless you plan to add that option, we can just close this issue?
