### ISSUE TITLE
Form select seems to break other uses of PowerSelect

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#71]
Not sure what the issue is, my powerselect input is in an overlay and I get this:

<img width="371" alt="Screen Shot 2020-05-26 at 2 57 20 PM" src="https://user-images.githubusercontent.com/34726/82939409-54b4ca80-9f61-11ea-9b13-18d69dab3d4a.png">

Note how even the arrow styles are changed.

**Comment by josemarluedke** [comment]
Humm, interesting. Yeah, the styles we apply for FormSelect (which uses PowerSelect) are global.

Using [this](https://github.com/josemarluedke/tailwindcss-ember-power-select) for styling PowerSelect.

**Comment by knownasilya** [comment]
Do I need to manually disable power select styles?

**Comment by knownasilya** [comment]
https://github.com/josemarluedke/tailwindcss-ember-power-select/issues/13 helps

**Comment by josemarluedke** [comment]
Ahh, interesting. So just adding autoprefixer fixes the original issue here?

**Comment by knownasilya** [comment]
Yup
