### ISSUE TITLE
Ember Basic Dropdown styles are not included

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/frontile#76]
When the host app doesn't directly depend on ember-basic-dropdown, the styles are not included. This results in `FormSelect` to not work out of the box.

**Comment by knownasilya** [comment]
What's the fix here?

**Comment by knownasilya** [comment]
Not sure it's the basic-dropdown styles, adding those manually doesn't seem to fix the issue. Why does this work in the docs app?
