### ISSUE TITLE
e2e example

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/frontile#83]
I know there is a note about "rewriting the docs", but maybe few hints that are not obvious from the perspective of the author: I am missing complete end-to-end example that would wire up all the common requirements together. And possibly explain what works how and why.

- [x] There is no mention of `@onSubmit={{this.save}}` on the `<ChangesetForm>` page. I thought I would have to wire up saving myself, but somehow the library does it for me. I can't see that information surfaced anywhere.
- [x] I [think](https://github.com/josemarluedke/frontile/blob/master/packages/changeset-form/addon/components/changeset-form/index.ts) that the way to handle saving completely manually I would have to: `<ChangesetForm @runExecuteInsteadOfSave={{true}} @onSubmit={{this.save}}>` is that the intended way?
- [x] I want to show flash message on successful save - how to wire that up?
- [x] Examples use native HTML `<button>` instead the provided one. I can see that the parts are independent and you might want to keep them that way, which is fine. Personally I'm a fan of great copy&paste examples, that will just work.

Feel free to just close this comment if it does not serve additional value.

p.s: Love the addon. Thanks for doing this.

**Comment by Baltazore** [comment]
@MichalBryxi thank you for saving my sanity this evening, your workaround for `execute` works on latest version as well 👍

**Comment by josemarluedke** [comment]
@MichalBryxi I have pushed a few new things to the docs, including a table of the arguments for ChangesetForm. Does that help with this issue? Should I close it?

**Comment by MichalBryxi** [comment]
Went through all the items and given that the user can see the possible arguments, I think this can be closed. This gives a good description of the API.
