### ISSUE TITLE
Use public {{in-element}} for overlay

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#95]
Can use a polyfill https://github.com/ember-polyfills/ember-in-element-polyfill

**Comment by knownasilya** [comment]
Seems like https://github.com/DockYard/ember-maybe-in-element is an unnecessary indirection, and where the private version is used.

**Comment by josemarluedke** [comment]
The ember-maybe-in-element is now using the public version of `in-element`. I do think we can drop this dependency, but I would wait until we can also drop the polyfill. That requires Ember  ^ 3.20. We might do that soon if we start using named blocks...

**Comment by josemarluedke** [comment]
I believe this is solved in the latest releases.
